// A little maze: guide the hero to the goal. Drag the hero along the path with a finger (it steps
// into each open square her finger reaches), or tap a glowing square next to it. The hero walks
// from square to square. A new maze each time (generated by a random depth-first walk).
import { useEffect, useMemo, useRef, useState } from 'react'
import type { Thing } from '../data/islands'
import { praise, speak } from '../lib/speech'
import { sfx } from '../lib/sfx'
import { shuffle, wait } from '../lib/util'
import { useAlive } from '../lib/useAlive'
import Pic from '../components/Pic'

const W = 6, H = 4

/** Open passages between cells, as a set of "a|b" keys (cells are numbered y * W + x). */
function makeMaze(): Set<string> {
  const open = new Set<string>()
  const seen = new Set<number>([0])
  const stack = [0]
  while (stack.length) {
    const c = stack[stack.length - 1]
    const x = c % W, y = Math.floor(c / W)
    const next = shuffle([[x + 1, y], [x - 1, y], [x, y + 1], [x, y - 1]])
      .filter(([nx, ny]) => nx >= 0 && ny >= 0 && nx < W && ny < H && !seen.has(ny * W + nx))
    if (!next.length) { stack.pop(); continue }
    const n = next[0][1] * W + next[0][0]
    open.add(`${Math.min(c, n)}|${Math.max(c, n)}`)
    seen.add(n)
    stack.push(n)
  }
  return open
}

/** `trail`: the mark left on squares the hero has been (default footprints); `theme: 'water'`: a sea maze. */
export default function Maze({ title, intro, hero, goal, trail: mark = '👣', theme, onDone }: {
  title: string; intro: string; hero: Thing; goal: Thing; trail?: string; theme?: 'water'; onDone: () => void
}) {
  const open = useMemo(makeMaze, [])
  const linked = (a: number, b: number) => open.has(`${Math.min(a, b)}|${Math.max(a, b)}`)
  const GOAL = W * H - 1
  const [at, setAt] = useState(0)
  const atRef = useRef(0)
  const [trail, setTrail] = useState<number[]>([0])
  const [won, setWon] = useState(false)
  // The hero turns the way it walks. (Animal emoji face left on the iPad, so -1 faces right.)
  const [facing, setFacing] = useState(-1)
  const finished = useRef(false) // a ref, so a double tap on the goal can't finish twice
  const dragging = useRef<number | null>(null)
  const nudged = useRef(0)
  const alive = useAlive()

  useEffect(() => { speak(intro) }, [])

  const neighbors = (c: number) => [c - W, c + W, c % W ? c - 1 : -1, c % W < W - 1 ? c + 1 : -1].filter((n) => n >= 0 && n < W * H && linked(c, n))
  const canGo = neighbors(at)

  /** One step to an open square next to the hero. */
  const step = async (c: number) => {
    const from = atRef.current
    if (finished.current || !neighbors(from).includes(c)) return false
    sfx.pop()
    if (c % W !== from % W) setFacing(c % W > from % W ? -1 : 1)
    atRef.current = c
    setAt(c)
    setTrail((t) => [...t, c])
    if (c !== GOAL) return true
    finished.current = true
    setWon(true)
    sfx.fanfare()
    await speak(`${praise()} You found ${goal.say}!`)
    if (!alive.current) return true
    await wait(500)
    if (alive.current) onDone()
    return true
  }

  const tap = (c: number) => {
    if (finished.current || dragging.current !== null) return
    if (!neighbors(atRef.current).includes(c)) {
      if (c !== atRef.current) { sfx.oops(); speak(`Tap a glowing square next to ${hero.say}, or drag ${hero.say} along!`) }
      return
    }
    step(c)
  }

  // Dragging the hero: every open square her finger moves into is a step.
  const cellAt = (x: number, y: number) => {
    const el = document.elementFromPoint(x, y)?.closest('[data-cell]')
    return el ? Number(el.getAttribute('data-cell')) : null
  }
  const down = (e: React.PointerEvent) => {
    if (finished.current) return
    const c = cellAt(e.clientX, e.clientY)
    if (c !== atRef.current) return
    dragging.current = e.pointerId
    try { (e.currentTarget as HTMLElement).setPointerCapture(e.pointerId) } catch { /* fine */ }
    sfx.lift()
  }
  const move = (e: React.PointerEvent) => {
    if (dragging.current !== e.pointerId) return
    const c = cellAt(e.clientX, e.clientY)
    if (c === null || c === atRef.current) return
    if (neighbors(atRef.current).includes(c)) step(c)
    else if (Date.now() - nudged.current > 900) { nudged.current = Date.now(); sfx.oops() } // a wall
  }
  const up = (e: React.PointerEvent) => {
    if (dragging.current !== e.pointerId) return
    // A drag that went nowhere was a tap on the hero: let the click through.
    setTimeout(() => { dragging.current = null }, 0)
  }

  const x = at % W, y = Math.floor(at / W)
  return (
    <div className={`activity maze ${theme ?? ''}`}>
      <h2>{title}</h2>
      <div className="maze-grid" style={{ gridTemplateColumns: `repeat(${W}, 1fr)` }} onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerCancel={up}>
        {Array.from({ length: W * H }, (_, c) => {
          const wall = (n: number, ok: boolean) => (ok && linked(c, n) ? 'transparent' : 'var(--maze-wall)')
          const cx = c % W
          return (
            <button key={c} data-cell={c} className={`maze-cell ${canGo.includes(c) && !won ? 'can' : ''}`} onClick={() => tap(c)}
              style={{
                borderTopColor: wall(c - W, c >= W), borderBottomColor: wall(c + W, c < W * (H - 1)),
                borderLeftColor: wall(c - 1, cx > 0), borderRightColor: wall(c + 1, cx < W - 1),
              }}>
              {c === GOAL ? <span className="maze-goal"><Pic e={goal.emoji} art={goal.art} /></span>
                : trail.includes(c) && c !== at ? <span className="maze-step"><Pic e={mark} /></span> : null}
            </button>
          )
        })}
        {/* The hero walks between squares (it isn't inside one), and can be dragged. */}
        <span className={`maze-hero ${won ? 'won' : ''}`} style={{ left: `${((x + 0.5) / W) * 100}%`, top: `${((y + 0.5) / H) * 100}%` }}>
          <span className="maze-hero-face" style={{ transform: `scaleX(${facing})` }}><Pic e={hero.emoji} art={hero.art} /></span>
        </span>
      </div>
      <button className="instruction" onClick={() => speak(intro)}>🔊 Hear it again</button>
    </div>
  )
}
