// A little maze: guide the hero to the goal. Squares next to the hero that she can step to glow;
// tapping one moves there. A new maze each time (generated by a random depth-first walk).
import { useEffect, useMemo, useRef, useState } from 'react'
import type { Thing } from '../data/islands'
import { praise, speak } from '../lib/speech'
import { sfx } from '../lib/sfx'
import { shuffle, wait } from '../lib/util'
import { useAlive } from '../lib/useAlive'

const W = 6, H = 4

/** Open passages between cells, as a set of "a|b" keys (cells are numbered y * W + x). */
function makeMaze(): Set<string> {
  const open = new Set<string>()
  const seen = new Set<number>([0])
  const stack = [0]
  while (stack.length) {
    const c = stack[stack.length - 1]
    const x = c % W, y = Math.floor(c / W)
    const next = shuffle([[x + 1, y], [x - 1, y], [x, y + 1], [x, y - 1]])
      .filter(([nx, ny]) => nx >= 0 && ny >= 0 && nx < W && ny < H && !seen.has(ny * W + nx))
    if (!next.length) { stack.pop(); continue }
    const n = next[0][1] * W + next[0][0]
    open.add(`${Math.min(c, n)}|${Math.max(c, n)}`)
    seen.add(n)
    stack.push(n)
  }
  return open
}

export default function Maze({ title, intro, hero, goal, onDone }: { title: string; intro: string; hero: Thing; goal: Thing; onDone: () => void }) {
  const open = useMemo(makeMaze, [])
  const linked = (a: number, b: number) => open.has(`${Math.min(a, b)}|${Math.max(a, b)}`)
  const GOAL = W * H - 1
  const [at, setAt] = useState(0)
  const [trail, setTrail] = useState<number[]>([0])
  const [won, setWon] = useState(false)
  const finished = useRef(false) // a ref, so a double tap on the goal can't finish twice
  const alive = useAlive()

  useEffect(() => { speak(intro) }, [])

  const neighbors = (c: number) => [c - W, c + W, c % W ? c - 1 : -1, c % W < W - 1 ? c + 1 : -1].filter((n) => n >= 0 && n < W * H && linked(c, n))
  const canGo = neighbors(at)

  const tap = async (c: number) => {
    if (finished.current) return
    if (!canGo.includes(c)) {
      if (c !== at) { sfx.oops(); speak(`Tap a glowing square next to ${hero.say}!`) }
      return
    }
    sfx.pop()
    setAt(c)
    setTrail((t) => [...t, c])
    if (c !== GOAL) return
    finished.current = true
    setWon(true)
    sfx.fanfare()
    await speak(`${praise()} You found ${goal.say}!`)
    if (!alive.current) return
    await wait(500)
    if (alive.current) onDone()
  }

  return (
    <div className="activity maze">
      <h2>{title}</h2>
      <div className="maze-grid" style={{ gridTemplateColumns: `repeat(${W}, 1fr)` }}>
        {Array.from({ length: W * H }, (_, c) => {
          const wall = (n: number, ok: boolean) => (ok && linked(c, n) ? 'transparent' : 'var(--maze-wall)')
          const x = c % W
          return (
            <button key={c} className={`maze-cell ${canGo.includes(c) && !won ? 'can' : ''}`} onClick={() => tap(c)}
              style={{
                borderTopColor: wall(c - W, c >= W), borderBottomColor: wall(c + W, c < W * (H - 1)),
                borderLeftColor: wall(c - 1, x > 0), borderRightColor: wall(c + 1, x < W - 1),
              }}>
              {c === at ? <span className={`maze-hero ${won ? 'won' : ''}`}>{hero.emoji}</span>
                : c === GOAL ? <span className="maze-goal">{goal.emoji}</span>
                : trail.includes(c) ? <span className="maze-step">👣</span> : null}
            </button>
          )
        })}
      </div>
      <button className="instruction" onClick={() => speak(intro)}>🔊 Hear it again</button>
    </div>
  )
}
